// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Advertisement is the predicate function for advertisement builders.
type Advertisement func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
