// Code generated by entc, DO NOT EDIT.

package users

const (
	// Label holds the string label denoting the users type in the database.
	Label = "users"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFistName holds the string denoting the fistname field in the database.
	FieldFistName = "fist_name"
	// FieldLastName holds the string denoting the lastname field in the database.
	FieldLastName = "last_name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// EdgeAdvertisement holds the string denoting the advertisement edge name in mutations.
	EdgeAdvertisement = "advertisement"
	// Table holds the table name of the users in the database.
	Table = "users"
	// AdvertisementTable is the table that holds the advertisement relation/edge.
	AdvertisementTable = "advertisements"
	// AdvertisementInverseTable is the table name for the Advertisement entity.
	// It exists in this package in order to avoid circular dependency with the "advertisement" package.
	AdvertisementInverseTable = "advertisements"
	// AdvertisementColumn is the table column denoting the advertisement relation/edge.
	AdvertisementColumn = "users_advertisement"
)

// Columns holds all SQL columns for users fields.
var Columns = []string{
	FieldID,
	FieldFistName,
	FieldLastName,
	FieldEmail,
	FieldPassword,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FistNameValidator is a validator for the "FistName" field. It is called by the builders before save.
	FistNameValidator func(string) error
	// LastNameValidator is a validator for the "LastName" field. It is called by the builders before save.
	LastNameValidator func(string) error
	// EmailValidator is a validator for the "Email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "Password" field. It is called by the builders before save.
	PasswordValidator func(string) error
)
